### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by Naxus28** [LyndaExerciseFiles/angular2-essential-training#15]
tsc && concurrently "tsc -w" "lite-server"  fail on my system

**Comment by Naxus28** [comment]
Fixed the problem by replacing the "scripts start" command on package.json:

`"start": "concurrently \"npm run tsc:w\" \"npm run lite\""`

**Comment by afide26** [comment]
Also fixed this by changing the target to es6 from es5
`{
  "compilerOptions": {
    "target": "es6",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  }
}`

**Comment by dusnoki** [comment]
A pull request would be nice for this.

**Comment by mikelbrownus** [comment]
While changing target from es5 to es6 does allow you to compile and run the project, it does not fix what is wrong with this project setup.  Presumably you want to still be compiling to es5.  Knowing what has gone wrong here is, uh ..., kind of important.  The real struggle in moving to Angular 2+ may well be the large setup overhead you need in project setup and the biggest drawback to the framework.

**Comment by jschwarty** [comment]
The Angular CLI helps to alleviate the project setup and build stuff for an
Angular app. I will make a branch for this project that uses the CLI to
help with this.

**Comment by anuraggautam77** [comment]
Failed to start the application after npm start command.

**Comment by jschwarty** [comment]
There is a newer repo for the lesson code for this course. That can be found at:
https://github.com/coursefiles/angular2-essential-training

Please clone that one down and see if you receive any of the above mentioned issues. If so, let me know either by a comment here or opening a new issue on the current repo at https://github.com/coursefiles/angular2-essential-training/issues

Thanks!
